// System call numbers
#define SYS_exit    1
#define SYS__exit    1
#define SYS_fork    2
#define SYS_read    3
#define SYS_write   4
#define SYS_open    5
#define SYS_close   6
#define SYS_wait    7
#define SYS_link    9
#define SYS_unlink  10
#define SYS_execve  11
#define SYS_chdir   12
#define SYS_uptime  13
#define SYS_mknod   14
#define SYS_pipe    42
#define SYS_kill    37
#define SYS_exec    283
#define SYS_fstat   108
#define SYS_dup     41
#define SYS_getpid  20
#define SYS_sbrk    45
#define SYS_sleep   162
#define SYS_mkdir   39
#define SYS_mmap    90
#define SYS_lseek   19
